spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db_for_create_liqui
    username: postgres # имя пользователя консоли
    password: 0 # пароль консоли
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.sql.dialect: org.hibernate.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  application.name: db_for_create_liqui